fix a bog

diff --git a/vendor/laravel/sail/bin/sail b/vendor/laravel/sail/bin/sail
--- a/vendor/laravel/sail/bin/sail
+++ b/vendor/laravel/sail/bin/sail
@@ -41,7 +41,9 @@ fi
 # Determine if Sail is currently up...
 PSRESULT="$(docker-compose ps -q)"
 
-if docker-compose ps | grep 'Exit' &> /dev/null; then
+if docker-compose ps | grep $APP_SERVICE | grep 'Exit'; then
+    echo -e "${WHITE}Shutting down old Sail processes...${NC}" >&2
+
     docker-compose down > /dev/null 2>&1
 
     EXEC="no"
@@ -75,6 +77,19 @@ if [ $# -gt 0 ]; then
                 -u sail \
                 "$APP_SERVICE" \
                 php "$@"
+        else
+            sail_is_not_running
+        fi
+
+    # Proxy vendor binary commands on the application container...
+    elif [ "$1" == "bin" ]; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                -u sail \
+                "$APP_SERVICE" \
+                ./vendor/bin/"$@"
         else
             sail_is_not_running
         fi
@@ -129,6 +144,21 @@ if [ $# -gt 0 ]; then
                 -e "DUSK_DRIVER_URL=http://selenium:4444/wd/hub" \
                 "$APP_SERVICE" \
                 php artisan dusk "$@"
+        else
+            sail_is_not_running
+        fi
+
+    # Proxy the "dusk:fails" command to the "php artisan dusk:fails" Artisan command...
+    elif [ "$1" == "dusk:fails" ]; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                -u sail \
+                -e "APP_URL=http://laravel.test" \
+                -e "DUSK_DRIVER_URL=http://selenium:4444/wd/hub" \
+                "$APP_SERVICE" \
+                php artisan dusk:fails "$@"
         else
             sail_is_not_running
         fi
@@ -205,7 +235,31 @@ if [ $# -gt 0 ]; then
         if [ "$EXEC" == "yes" ]; then
             docker-compose exec \
                 mysql \
-                bash -c 'MYSQL_PWD=${MYSQL_ROOT_PASSWORD} mysql -u ${MYSQL_USER} ${MYSQL_DATABASE}'
+                bash -c 'MYSQL_PWD=${MYSQL_PASSWORD} mysql -u ${MYSQL_USER} ${MYSQL_DATABASE}'
+        else
+            sail_is_not_running
+        fi
+
+    # Initiate a MySQL CLI terminal session within the "mariadb" container...
+    elif [ "$1" == "mariadb" ]; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                mariadb \
+                bash -c 'MYSQL_PWD=${MYSQL_PASSWORD} mysql -u ${MYSQL_USER} ${MYSQL_DATABASE}'
+        else
+            sail_is_not_running
+        fi
+
+    # Initiate a PostgreSQL CLI terminal session within the "pgsql" container...
+    elif [ "$1" == "psql" ]; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                 pgsql \
+                 bash -c 'PGPASSWORD=${PGPASSWORD} psql -U ${POSTGRES_USER} ${POSTGRES_DB}'
         else
             sail_is_not_running
         fi
@@ -235,12 +289,24 @@ if [ $# -gt 0 ]; then
             sail_is_not_running
         fi
 
+    # Initiate a Redis CLI terminal session within the "redis" container...
+    elif [ "$1" == "redis" ] ; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                redis \
+                redis-cli
+        else
+            sail_is_not_running
+        fi
+
     # Share the site...
     elif [ "$1" == "share" ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker run --init beyondcodegmbh/expose-server share http://host.docker.internal:"$APP_PORT" \
+            docker run --init beyondcodegmbh/expose-server:latest share http://host.docker.internal:"$APP_PORT" \
             --server-host=laravel-sail.site \
             --server-port=8080 \
             "$@"
